import Link from "next/link";
import { ArrowRight, BarChart3, Check, ExternalLink, Footprints, Layers3, PackagePlus, ShoppingBag, Sparkles, Store, UploadCloud } from "lucide-react";
import { LandingNav } from "@/components/landing-nav";
import { Logo } from "@/components/logo";
import { AudienceExperience, CapabilityExplorer, HeroDiscoveryDemo, StoryCarousel } from "@/components/marketing-showcases";

const industryCards = [
  { title: "Fashion & footwear", copy: "Guide fit, feel, intended use and personal style—not just size and colour.", icon: Footprints, color: "bg-[#ffd5b6]", number: "01" },
  { title: "Beauty & wellness", copy: "Translate routines, goals and preferences into reassuring product choices.", icon: Sparkles, color: "bg-lime", number: "02" },
  { title: "Home & lifestyle", copy: "Make taste-led and feature-heavy purchases easier to understand.", icon: Store, color: "bg-[#cbd9d0]", number: "03" },
  { title: "Sports & outdoors", copy: "Match conditions, goals and experience levels to the right equipment.", icon: ShoppingBag, color: "bg-[#d7d4ff]", number: "04" },
];

const stack = [
  ["CSV", "Catalog import"], ["HTML", "Any storefront"], ["JS", "Embed widget"], ["S", "Supabase"], ["AI", "OpenAI"], ["V", "Vercel"], ["API", "Secure routes"], ["↗", "Product links"],
];

export default function LandingPage() {
  return (
    <main className="overflow-hidden bg-white text-ink">
      <LandingNav />

      <section className="relative px-5 pb-28 pt-20 lg:px-8 lg:pb-36 lg:pt-28">
        <div className="absolute left-1/2 top-16 h-[480px] w-[1000px] -translate-x-1/2 rounded-full bg-[radial-gradient(circle,rgba(217,255,97,.24),transparent_67%)]" />
        <div className="relative mx-auto max-w-[1280px] text-center">
          <div className="inline-flex items-center gap-2 text-xs font-extrabold uppercase tracking-[.16em] text-moss"><span className="h-2 w-2 rounded-full bg-lime shadow-[0_0_0_5px_rgba(217,255,97,.25)]" />AI-guided product discovery for ecommerce</div>
          <h1 className="mx-auto mt-8 max-w-[1120px] text-[4rem] font-extrabold leading-[.91] tracking-[-.075em] sm:text-[5.7rem] lg:text-[7.15rem]">
            Turn product choice<br /><span className="bg-[linear-gradient(90deg,#45624f_0%,#6b8c49_45%,#b3d930_100%)] bg-clip-text text-transparent">into confident</span><br />purchases.
          </h1>
          <p className="mx-auto mt-8 max-w-[740px] text-base leading-7 text-black/55 sm:text-lg">Findly unifies your product catalog, buying questions, recommendation rules, AI explanations and journey analytics into one focused guided-selling engine.</p>
          <div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/signup" className="inline-flex items-center justify-center gap-2 rounded-full bg-ink px-7 py-4 text-sm font-extrabold text-white transition hover:-translate-y-0.5 hover:bg-moss">Start building free <ArrowRight size={16} className="text-lime" /></Link><Link href="#platform" className="inline-flex items-center justify-center gap-2 rounded-full border border-black/15 bg-white px-7 py-4 text-sm font-extrabold transition hover:-translate-y-0.5 hover:border-black/35">See the platform</Link></div>
          <div className="mt-7 flex flex-wrap justify-center gap-x-7 gap-y-2 text-xs font-bold text-black/40"><span className="flex items-center gap-1.5"><Check size={12} />No card required</span><span className="flex items-center gap-1.5"><Check size={12} />Interactive demo included</span><span className="flex items-center gap-1.5"><Check size={12} />Launch with one snippet</span></div>
        </div>
        <div className="relative mx-auto mt-20 max-w-[1280px]"><HeroDiscoveryDemo /></div>
      </section>

      <section className="border-y border-black/[0.08] bg-white">
        <div className="mx-auto grid max-w-[1440px] divide-y divide-black/[0.07] lg:grid-cols-[1.1fr_1fr] lg:divide-x lg:divide-y-0">
          <div className="grid grid-cols-4 divide-x divide-black/[0.07]">{[["<60 sec", "to a result"], ["1–3", "best matches"], ["5", "journey events"], ["1", "embed snippet"]].map(([value, label]) => <div key={label} className="px-3 py-8 text-center"><p className="text-2xl font-extrabold tracking-[-.05em] sm:text-3xl">{value}</p><p className="mt-1 text-xs font-bold text-black/35">{label}</p></div>)}</div>
          <div className="flex items-center justify-center gap-8 overflow-hidden px-6 py-8 text-xs font-extrabold uppercase tracking-[.12em] text-black/25"><span className="text-black/45">Built for modern commerce</span><span>Northstar</span><span>Form / Co.</span><span>Wellmade</span><span>Hinterland</span></div>
        </div>
      </section>

      <section id="why" className="relative bg-[linear-gradient(135deg,#f8faf2_0%,#f1f4e5_46%,#fff4eb_100%)] px-5 py-28 lg:px-8 lg:py-36">
        <div className="absolute inset-0 dot-grid opacity-15" />
        <div className="relative mx-auto max-w-[1280px]">
          <div className="grid gap-8 lg:grid-cols-[1.2fr_.8fr] lg:items-end"><div><p className="eyebrow text-moss">One focused platform</p><h2 className="mt-5 max-w-4xl text-5xl font-extrabold leading-[.98] tracking-[-.065em] sm:text-7xl lg:text-[5.6rem]">Built for both the shopper <span className="text-moss">and the team</span> behind the store.</h2></div><p className="max-w-md text-sm leading-7 text-black/50 lg:justify-self-end">One engine, two sides of the same decision. Findly helps customers understand what fits while giving commerce teams control over how every recommendation is made.</p></div>
          <div className="mt-16"><AudienceExperience /></div>
        </div>
      </section>

      <section id="platform" className="bg-[#f8f6f1] px-5 py-28 lg:px-8 lg:py-36">
        <div className="mx-auto max-w-[1280px]">
          <div className="text-center"><p className="eyebrow text-moss">The Findly engine</p><h2 className="mx-auto mt-5 max-w-4xl text-5xl font-extrabold leading-[.98] tracking-[-.065em] sm:text-7xl">Every capability you need for <span className="text-moss">guided discovery.</span></h2><p className="mx-auto mt-6 max-w-2xl text-sm leading-6 text-black/50">Start with a catalog and a few thoughtful questions. Findly brings the logic, explanation, delivery and learning loop together.</p></div>
          <div className="mt-16"><CapabilityExplorer /></div>
        </div>
      </section>

      <section id="how" className="bg-white px-5 py-28 lg:px-8 lg:py-36">
        <div className="mx-auto max-w-[1280px]">
          <div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="eyebrow text-moss">From catalog to conversion</p><p className="mt-5 max-w-sm text-sm leading-7 text-black/50">No complex rollout. Bring the product knowledge you already have, shape the questions, and publish a polished customer experience.</p></div><h2 className="text-5xl font-extrabold leading-[.98] tracking-[-.065em] sm:text-7xl lg:text-right">Live before your<br /><span className="text-moss">next coffee.</span></h2></div>
          <div className="mt-16 grid gap-px overflow-hidden rounded-[30px] border border-black/10 bg-black/10 lg:grid-cols-3">{[
            { n: "01", title: "Bring your catalog", copy: "Upload a CSV or add products manually, including every attribute the matching engine should understand.", icon: UploadCloud },
            { n: "02", title: "Shape the conversation", copy: "Create questions and connect each answer to product tags, categories, features or a customer’s budget.", icon: Layers3 },
            { n: "03", title: "Publish and learn", copy: "Copy the widget snippet, go live, and track the signals from first view through to product click.", icon: BarChart3 },
          ].map(({ n, title, copy, icon: Icon }) => <article key={n} className="group bg-white p-8 transition hover:bg-[#f4f7eb] sm:p-10"><div className="flex items-start justify-between"><span className="text-xs font-extrabold tracking-[.16em] text-moss">{n}</span><span className="grid h-12 w-12 place-items-center rounded-2xl bg-lime/45 transition group-hover:bg-lime"><Icon size={20} /></span></div><h3 className="mt-16 text-3xl font-extrabold tracking-[-.055em]">{title}</h3><p className="mt-4 max-w-sm text-sm leading-6 text-black/48">{copy}</p><Link href={n === "01" ? "/dashboard/products" : n === "02" ? "/dashboard/quizzes" : "/dashboard/settings"} className="mt-8 inline-flex items-center gap-2 text-xs font-extrabold text-moss">Explore <ArrowRight size={13} /></Link></article>)}</div>
        </div>
      </section>

      <section className="bg-ink px-5 py-28 text-white lg:px-8 lg:py-36">
        <div className="mx-auto max-w-[1280px]">
          <div className="text-center"><p className="eyebrow text-lime">Product truth, not AI guesswork</p><h2 className="mx-auto mt-5 max-w-4xl text-5xl font-extrabold leading-[.98] tracking-[-.065em] sm:text-7xl">Selection stays reliable.<br /><span className="text-lime">Explanation feels human.</span></h2><p className="mx-auto mt-6 max-w-2xl text-sm leading-6 text-white/45">Findly’s hybrid system keeps AI in the role it is best at. Rules select products deterministically; AI explains the match using only the customer answers and catalog facts supplied.</p></div>
          <div className="mt-16 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[
            ["01", "Eligibility", "Inactive and over-budget products are excluded before ranking."], ["02", "Rule scoring", "Tags, categories and features add transparent weighted signals."], ["03", "Stable ranking", "Score, price and name tie-breakers keep results repeatable."], ["04", "Grounded copy", "AI receives only selected product facts and shopper answers."],
          ].map(([number, title, copy]) => <div key={number} className="rounded-2xl border border-white/10 bg-white/[.04] p-6"><span className="text-xs font-extrabold text-lime">{number}</span><h3 className="mt-12 text-xl font-extrabold tracking-[-.03em]">{title}</h3><p className="mt-3 text-xs leading-5 text-white/40">{copy}</p></div>)}</div>
          <div className="mt-4 grid overflow-hidden rounded-[28px] border border-white/10 bg-white/[.04] lg:grid-cols-[.9fr_1.1fr]"><div className="p-8 sm:p-12"><p className="eyebrow text-lime">A real match, step by step</p><h3 className="mt-5 text-4xl font-extrabold leading-tight tracking-[-.055em]">A recommendation your team can understand.</h3><p className="mt-4 text-sm leading-6 text-white/45">Every result is traceable to a small set of visible product signals. No opaque black box deciding what your customers see.</p><Link href="/finder/quiz_footwear" className="mt-8 inline-flex items-center gap-2 rounded-full bg-lime px-5 py-3 text-xs font-extrabold text-ink">Try the live match <ArrowRight size={14} /></Link></div><div className="bg-[radial-gradient(circle_at_75%_20%,rgba(217,255,97,.22),transparent_38%)] p-8 sm:p-12"><div className="rounded-2xl border border-white/10 bg-white/[.06] p-5"><div className="flex items-center justify-between"><span className="text-xs font-extrabold text-white/50">Recommendation trace</span><span className="rounded-full bg-lime px-2.5 py-1 text-xs font-extrabold text-ink">94% match</span></div><div className="mt-5 space-y-3">{[["Customer answer", "Weekend trails"], ["Matched tag", "trail · weight 5"], ["Matched feature", "high cushioning · weight 3"], ["Budget check", "£128 ≤ £140"], ["Selected product", "Terra Trail Runner"]].map(([label, value], i) => <div key={label} className="flex items-center gap-3 rounded-xl bg-white/[.05] p-3"><span className={`grid h-7 w-7 place-items-center rounded-lg text-xs font-extrabold ${i === 4 ? "bg-lime text-ink" : "bg-white/10"}`}>{i + 1}</span><span className="text-xs text-white/35">{label}</span><span className="ml-auto text-xs font-extrabold">{value}</span></div>)}</div></div></div></div>
        </div>
      </section>

      <section id="industries" className="bg-white px-5 py-28 lg:px-8 lg:py-36">
        <div className="mx-auto max-w-[1280px]"><p className="eyebrow text-moss">Made for considered purchases</p><div className="mt-5 flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><h2 className="max-w-4xl text-5xl font-extrabold leading-[.98] tracking-[-.065em] sm:text-7xl">Built for the catalogs<br /><span className="text-moss">that need guidance.</span></h2><p className="max-w-sm text-sm leading-6 text-black/50">Whenever “which one?” slows the sale, a short guided experience can turn uncertainty into momentum.</p></div><div className="mt-14 grid gap-4 sm:grid-cols-2">{industryCards.map(({ title, copy, icon: Icon, color, number }) => <article key={title} className={`group relative min-h-[330px] overflow-hidden rounded-[28px] border border-black/10 p-8 ${color}`}><div className="dot-grid absolute inset-0 opacity-15" /><div className="relative flex h-full flex-col"><div className="flex items-start justify-between"><span className="text-xs font-extrabold tracking-wider">{number}</span><span className="grid h-14 w-14 place-items-center rounded-2xl border border-black/10 bg-white/55 backdrop-blur transition group-hover:rotate-6 group-hover:scale-105"><Icon size={23} /></span></div><div className="mt-auto pt-24"><h3 className="text-3xl font-extrabold tracking-[-.055em]">{title}</h3><p className="mt-3 max-w-md text-sm leading-6 text-black/55">{copy}</p></div></div></article>)}</div></div>
      </section>

      <section className="bg-[#f2f4ee] px-5 py-28 lg:px-8 lg:py-36"><div className="mx-auto max-w-[1280px]"><p className="eyebrow text-moss">How Findly fits</p><h2 className="mt-5 max-w-4xl text-5xl font-extrabold leading-[.98] tracking-[-.065em] sm:text-7xl">Designed around the jobs<br /><span className="text-moss">commerce teams actually do.</span></h2><div className="mt-14"><StoryCarousel /></div></div></section>

      <section className="bg-white px-5 py-28 lg:px-8 lg:py-36"><div className="mx-auto grid max-w-[1280px] gap-12 lg:grid-cols-[.72fr_1.28fr] lg:items-center"><div><p className="eyebrow text-moss">A practical modern stack</p><h2 className="mt-5 text-5xl font-extrabold leading-[.98] tracking-[-.065em] sm:text-6xl">Works with the tools your MVP relies on.</h2><p className="mt-5 max-w-md text-sm leading-6 text-black/50">Import catalog data by CSV, publish to any HTML storefront, and run the production app on Supabase, OpenAI and Vercel.</p><Link href="/signup" className="mt-7 inline-flex items-center gap-2 text-xs font-extrabold text-moss">Start your workspace <ArrowRight size={13} /></Link></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{stack.map(([mark, label]) => <div key={label} className="group grid min-h-[150px] place-items-center rounded-2xl border border-black/10 bg-white p-5 text-center transition hover:-translate-y-1 hover:shadow-lg"><span><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[#f0f2ec] text-sm font-extrabold text-moss transition group-hover:bg-lime">{mark}</span><span className="mt-3 block text-xs font-extrabold">{label}</span></span></div>)}</div></div></section>

      <section id="resources" className="bg-[#f8f6f1] px-5 py-28 lg:px-8 lg:py-36"><div className="mx-auto max-w-[1280px]"><div className="flex items-end justify-between gap-6"><div><p className="eyebrow text-moss">Resources</p><h2 className="mt-5 text-5xl font-extrabold tracking-[-.065em] sm:text-7xl">See how it works.</h2></div><Link href="/signup" className="hidden items-center gap-2 text-xs font-extrabold text-moss sm:flex">Start building <ArrowRight size={13} /></Link></div><div className="mt-14 grid gap-4 lg:grid-cols-4">{[
        { label: "Interactive demo", title: "Answer three questions and meet your best product matches.", href: "/finder/quiz_footwear", icon: Sparkles, color: "bg-lime" },
        { label: "Merchant workspace", title: "Explore catalog tools, the visual builder, analytics and embed settings.", href: "/login", icon: BarChart3, color: "bg-[#d7d4ff]" },
        { label: "Conversational advisor", title: "Describe what you need naturally and get grounded catalog matches.", href: "/assistant/quiz_footwear", icon: Sparkles, color: "bg-[#ffd5b6]" },
        { label: "Visual configurator", title: "Build a compatible trail kit while price and checkout links update.", href: "/configurator/config_trail_kit", icon: PackagePlus, color: "bg-[#cbd9d0]" },
      ].map(({ label, title, href, icon: Icon, color }) => <Link key={label} href={href} className="group overflow-hidden rounded-[26px] border border-black/10 bg-white"><div className={`relative grid h-52 place-items-center ${color}`}><div className="dot-grid absolute inset-0 opacity-20" /><span className="relative grid h-20 w-20 place-items-center rounded-[24px] border border-black/10 bg-white/65 backdrop-blur transition group-hover:rotate-6 group-hover:scale-105"><Icon size={29} /></span></div><div className="p-7"><p className="eyebrow text-moss">{label}</p><h3 className="mt-4 text-xl font-extrabold leading-snug tracking-[-.035em]">{title}</h3><span className="mt-6 inline-flex items-center gap-2 text-xs font-extrabold text-moss">Explore <ArrowRight size={13} /></span></div></Link>)}</div></div></section>

      <section id="pricing" className="bg-white px-5 py-28 lg:px-8 lg:py-36"><div className="mx-auto grid max-w-[1280px] overflow-hidden rounded-[32px] border border-black/10 lg:grid-cols-[.78fr_1.22fr]"><div className="relative overflow-hidden bg-lime p-9 sm:p-14"><div className="dot-grid absolute inset-0 opacity-20" /><div className="relative"><p className="eyebrow">Early-access pricing</p><h2 className="mt-5 text-5xl font-extrabold leading-[.96] tracking-[-.065em] sm:text-6xl">Start small.<br />Prove the idea.<br />Grow later.</h2><p className="mt-6 max-w-md text-sm leading-6 text-black/55">The MVP is free to explore while the core guided-selling workflow is being proven.</p></div></div><div className="p-9 sm:p-14"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div><span className="rounded-full bg-[#f1f3ed] px-3 py-1.5 text-xs font-extrabold uppercase tracking-wider">Starter workspace</span><h3 className="mt-5 text-2xl font-extrabold">Everything in the MVP</h3></div><div><span className="text-5xl font-extrabold tracking-[-.06em]">£0</span><span className="text-xs text-black/35"> / month</span></div></div><div className="my-8 h-px bg-black/10" /><div className="grid gap-3 sm:grid-cols-2">{["Product catalog and CSV import", "Visual finder builder", "Visual configurator builder", "Deterministic recommendation engine", "AI match explanations", "Embeddable modal widget", "Core journey analytics", "Brand settings", "Demo data to explore"].map((item) => <span key={item} className="flex items-center gap-2 text-xs font-extrabold"><span className="grid h-5 w-5 place-items-center rounded-full bg-lime"><Check size={11} /></span>{item}</span>)}</div><Link href="/signup" className="mt-9 inline-flex w-full items-center justify-center gap-2 rounded-full bg-ink px-6 py-4 text-sm font-extrabold text-white">Create your workspace <ArrowRight size={15} className="text-lime" /></Link></div></div></section>

      <section className="px-5 pb-5 lg:px-8"><div className="relative mx-auto max-w-[1440px] overflow-hidden rounded-[34px] bg-ink px-6 py-24 text-center text-white sm:px-12"><div className="absolute -left-24 -top-24 h-80 w-80 rounded-full bg-lime/20 blur-3xl" /><div className="absolute -bottom-24 -right-24 h-80 w-80 rounded-full bg-peach/15 blur-3xl" /><div className="dot-grid absolute inset-0 opacity-10" /><div className="relative"><p className="eyebrow text-lime">The right product is already in your catalog</p><h2 className="mx-auto mt-6 max-w-5xl text-5xl font-extrabold leading-[.95] tracking-[-.07em] sm:text-7xl lg:text-[5.6rem]">Help every customer<br />find it.</h2><p className="mx-auto mt-6 max-w-xl text-sm leading-6 text-white/45">Turn your product expertise into a guided buying experience that works around the clock.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/signup" className="inline-flex items-center justify-center gap-2 rounded-full bg-lime px-7 py-4 text-sm font-extrabold text-ink">Start building free <ArrowRight size={15} /></Link><Link href="/finder/quiz_footwear" className="inline-flex items-center justify-center gap-2 rounded-full border border-white/15 px-7 py-4 text-sm font-extrabold text-white">Try the live finder <ExternalLink size={14} /></Link></div></div></div></section>

      <footer className="bg-white px-5 py-14 lg:px-8"><div className="mx-auto max-w-[1280px]"><div className="grid gap-12 border-b border-black/10 pb-12 lg:grid-cols-[1.3fr_repeat(4,1fr)]"><div><Logo /><p className="mt-5 max-w-xs text-xs leading-5 text-black/40">AI-guided product discovery for ecommerce teams that want useful recommendations without enterprise complexity.</p></div>{[
        ["Platform", [["Overview", "/platform"], ["Products", "/dashboard/products"], ["Finder builder", "/dashboard/quizzes"], ["Configurators", "/dashboard/configurators"], ["Analytics", "/dashboard/analytics"], ["Embed", "/dashboard/settings"]]],
        ["Experiences", [["Live finder", "/finder/quiz_footwear"], ["Advisor", "/assistant/quiz_footwear"], ["Configurator", "/configurator/config_trail_kit"], ["Merchant demo", "/login"], ["Industries", "/industries"]]],
        ["Company", [["Why Findly", "#why"], ["Pricing", "#pricing"], ["Start free", "/signup"], ["Contact", "mailto:hello@findly.app"]]],
        ["Product", [["Sign up", "/signup"], ["Log in", "/login"], ["Documentation", "/resources"], ["Setup guide", "/resources"]]],
      ].map(([heading, links]) => <div key={String(heading)}><h3 className="text-xs font-extrabold uppercase tracking-[.14em] text-black/35">{String(heading)}</h3><div className="mt-5 space-y-3">{(links as string[][]).map(([label, href]) => <Link key={label} href={href} className="block text-xs font-bold text-black/55 hover:text-ink">{label}</Link>)}</div></div>)}</div><div className="flex flex-col gap-4 pt-7 text-xs font-bold text-black/35 sm:flex-row sm:items-center sm:justify-between"><span>© 2026 Findly. Product decisions, made lighter.</span><div className="flex gap-6"><span>Privacy</span><span>Terms</span><span>Built with Next.js, Supabase & OpenAI</span></div></div></div></footer>
    </main>
  );
}
