import Link from "next/link";
import { ArrowRight, BarChart3, Check, ExternalLink, Footprints, Layers3, ShoppingBag, Sparkles, Store, UploadCloud } from "lucide-react";
import { LandingNav } from "@/components/landing-nav";
import { MarketingFooter } from "@/components/marketing-footer";
import { AudienceExperience, CapabilityExplorer, HeroDiscoveryDemo, StoryCarousel } from "@/components/marketing-showcases";

const industryCards = [
  { title: "Fashion & footwear", copy: "Guide fit, feel, intended use and personal style—not just size and colour.", icon: Footprints, color: "bg-[#ffd5b6]", number: "01" },
  { title: "Beauty & wellness", copy: "Translate routines, goals and preferences into reassuring product choices.", icon: Sparkles, color: "bg-lime", number: "02" },
  { title: "Home & lifestyle", copy: "Make taste-led and feature-heavy purchases easier to understand.", icon: Store, color: "bg-[#cbd9d0]", number: "03" },
  { title: "Sports & outdoors", copy: "Match conditions, goals and experience levels to the right equipment.", icon: ShoppingBag, color: "bg-[#d7d4ff]", number: "04" },
];

const stack = [
  ["CSV", "Catalog import"], ["HTML", "Any storefront"], ["JS", "Embed widget"], ["S", "Supabase"], ["AI", "OpenAI"], ["V", "Vercel"], ["API", "Secure routes"], ["↗", "Product links"],
];

export default function LandingPage() {
  return (
    <main className="overflow-hidden bg-white text-ink">
      <LandingNav />

      <section className="relative px-5 pb-24 pt-16 lg:px-8 lg:pb-32 lg:pt-20">
        <div className="absolute left-1/2 top-16 h-[480px] w-[1000px] -translate-x-1/2 rounded-full bg-[radial-gradient(circle,rgba(217,255,97,.24),transparent_67%)]" />
        <div className="relative mx-auto max-w-[1280px] text-center">
          <div className="inline-flex items-center gap-2 text-xs font-extrabold uppercase tracking-[.16em] text-moss"><span className="h-2 w-2 rounded-full bg-lime shadow-[0_0_0_5px_rgba(217,255,97,.25)]" />AI product finder widget for ecommerce stores</div>
          <h1 className="mx-auto mt-6 max-w-[1040px] text-[4rem] font-extrabold leading-[.91] tracking-[-.075em] sm:text-[5.25rem] lg:text-[6.35rem]">
            <span className="block">Help shoppers </span>
            <span className="block bg-[linear-gradient(90deg,#45624f_0%,#6b8c49_45%,#b3d930_100%)] bg-clip-text text-transparent">choose the right </span>
            <span className="block">product.</span>
          </h1>
          <p className="mx-auto mt-6 max-w-[760px] text-base leading-7 text-black/55 sm:text-lg">Sellentum lets an ecommerce brand upload its products, ask shoppers a few guided questions, recommend 1–3 best-fit products, explain why they fit, and embed the experience on any storefront with one script.</p>
          <div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/signup" className="inline-flex items-center justify-center gap-2 rounded-full bg-ink px-7 py-4 text-sm font-extrabold text-white transition hover:-translate-y-0.5 hover:bg-moss">Create your product finder <ArrowRight size={16} className="text-lime" /></Link><Link href="/finder/quiz_footwear" className="inline-flex items-center justify-center gap-2 rounded-full border border-black/15 bg-white px-7 py-4 text-sm font-extrabold transition hover:-translate-y-0.5 hover:border-black/35">Try the shopper demo</Link></div>
          <div className="mt-5 flex flex-wrap justify-center gap-x-7 gap-y-2 text-xs font-bold text-black/40"><span className="flex items-center gap-1.5"><Check size={12} />Upload products</span><span className="flex items-center gap-1.5"><Check size={12} />Ask guided questions</span><span className="flex items-center gap-1.5"><Check size={12} />Embed with one snippet</span></div>
        </div>
        <div className="relative mx-auto mt-12 max-w-[1280px]"><HeroDiscoveryDemo /></div>
      </section>

      <section className="border-y border-black/[0.08] bg-white">
        <div className="mx-auto grid max-w-[1440px] divide-y divide-black/[0.07] lg:grid-cols-[1.1fr_1fr] lg:divide-x lg:divide-y-0">
          <div className="grid grid-cols-4 divide-x divide-black/[0.07]">{[["CSV", "product upload"], ["3–5", "guided questions"], ["1–3", "best matches"], ["1", "embed snippet"]].map(([value, label]) => <div key={label} className="px-3 py-8 text-center"><p className="text-2xl font-extrabold tracking-[-.05em] sm:text-3xl">{value}</p><p className="mt-1 text-xs font-bold text-black/35">{label}</p></div>)}</div>
          <div className="flex items-center justify-center px-6 py-8 text-center text-sm font-extrabold tracking-[-.02em] text-black/45">Built for stores where shoppers keep asking: “Which product is right for me?”</div>
        </div>
      </section>

      <section id="why" className="relative bg-[linear-gradient(135deg,#f8faf2_0%,#f1f4e5_46%,#fff4eb_100%)] px-5 py-28 lg:px-8 lg:py-36">
        <div className="absolute inset-0 dot-grid opacity-15" />
        <div className="relative mx-auto max-w-[1280px]">
          <div className="grid gap-8 lg:grid-cols-[1.2fr_.8fr] lg:items-end"><div><p className="eyebrow text-moss">What Sellentum does</p><h2 className="mt-5 max-w-4xl text-5xl font-extrabold leading-[.98] tracking-[-.065em] sm:text-7xl lg:text-[5.6rem]">A guided product finder for shoppers, <span className="text-moss">a controlled sales tool</span> for your store.</h2></div><p className="max-w-md text-sm leading-7 text-black/50 lg:justify-self-end">Your shoppers get a helpful buying conversation. Your team gets control over the catalog, rules, widget and analytics behind every recommendation.</p></div>
          <div className="mt-16"><AudienceExperience /></div>
        </div>
      </section>

      <section id="platform" className="bg-[#f8f6f1] px-5 py-28 lg:px-8 lg:py-36">
        <div className="mx-auto max-w-[1280px]">
          <div className="text-center"><p className="eyebrow text-moss">How the service works</p><h2 className="mx-auto mt-5 max-w-4xl text-5xl font-extrabold leading-[.98] tracking-[-.065em] sm:text-7xl">Everything needed to launch <span className="text-moss">your first product finder.</span></h2><p className="mx-auto mt-6 max-w-2xl text-sm leading-6 text-black/50">Sellentum is intentionally simple at the start: product data in, buying questions in, recommendations and explanations out, then analytics to prove the journey works.</p></div>
          <div className="mt-16"><CapabilityExplorer /></div>
        </div>
      </section>

      <section id="how" className="bg-white px-5 py-28 lg:px-8 lg:py-36">
        <div className="mx-auto max-w-[1280px]">
          <div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="eyebrow text-moss">From catalog to customer guidance</p><p className="mt-5 max-w-sm text-sm leading-7 text-black/50">No complex rollout. Bring the product knowledge you already have, shape the questions, and publish a polished customer experience.</p></div><h2 className="text-5xl font-extrabold leading-[.98] tracking-[-.065em] sm:text-7xl lg:text-right"><span className="block">Launch a useful </span><span className="block text-moss">product finder.</span></h2></div>
          <div className="mt-16 grid gap-px overflow-hidden rounded-[30px] border border-black/10 bg-black/10 lg:grid-cols-3">{[
            { n: "01", title: "Upload your products", copy: "Add the names, prices, images, categories, tags, features and product URLs Sellentum needs to compare options.", icon: UploadCloud },
            { n: "02", title: "Ask the right questions", copy: "Create a short guided flow and connect each answer to product tags, categories, features or budget.", icon: Layers3 },
            { n: "03", title: "Embed and measure", copy: "Copy the widget snippet, go live, and track the path from first view through to Buy Now click.", icon: BarChart3 },
          ].map(({ n, title, copy, icon: Icon }) => <article key={n} className="group bg-white p-8 transition hover:bg-[#f4f7eb] sm:p-10"><div className="flex items-start justify-between"><span className="text-xs font-extrabold tracking-[.16em] text-moss">{n}</span><span className="grid h-12 w-12 place-items-center rounded-2xl bg-lime/45 transition group-hover:bg-lime"><Icon size={20} /></span></div><h3 className="mt-16 text-3xl font-extrabold tracking-[-.055em]">{title}</h3><p className="mt-4 max-w-sm text-sm leading-6 text-black/48">{copy}</p><Link href={n === "01" ? "/dashboard/products" : n === "02" ? "/dashboard/quizzes" : "/dashboard/settings"} className="mt-8 inline-flex items-center gap-2 text-xs font-extrabold text-moss">Explore <ArrowRight size={13} /></Link></article>)}</div>
        </div>
      </section>

      <section className="bg-ink px-5 py-28 text-white lg:px-8 lg:py-36">
        <div className="mx-auto max-w-[1280px]">
          <div className="text-center"><p className="eyebrow text-lime">Rules choose. AI explains.</p><h2 className="mx-auto mt-5 max-w-4xl text-5xl font-extrabold leading-[.98] tracking-[-.065em] sm:text-7xl"><span className="block">Reliable selection. </span><span className="block text-lime">Human explanations.</span></h2><p className="mx-auto mt-6 max-w-2xl text-sm leading-6 text-white/45">Sellentum does not let AI randomly choose products. Your rules select the best matches first; AI then explains each recommendation using the shopper’s answers and your catalog facts.</p></div>
          <div className="mt-16 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[
            ["01", "Eligibility", "Inactive and over-budget products are excluded before ranking."], ["02", "Rule scoring", "Tags, categories and features add transparent weighted signals."], ["03", "Stable ranking", "Score, price and name tie-breakers keep results repeatable."], ["04", "Grounded copy", "AI receives only selected product facts and shopper answers."],
          ].map(([number, title, copy]) => <div key={number} className="rounded-2xl border border-white/10 bg-white/[.04] p-6"><span className="text-xs font-extrabold text-lime">{number}</span><h3 className="mt-12 text-xl font-extrabold tracking-[-.03em]">{title}</h3><p className="mt-3 text-xs leading-5 text-white/40">{copy}</p></div>)}</div>
          <div className="mt-4 grid overflow-hidden rounded-[28px] border border-white/10 bg-white/[.04] lg:grid-cols-[.9fr_1.1fr]"><div className="p-8 sm:p-12"><p className="eyebrow text-lime">A real match, step by step</p><h3 className="mt-5 text-4xl font-extrabold leading-tight tracking-[-.055em]">A recommendation your team can understand.</h3><p className="mt-4 text-sm leading-6 text-white/45">Every result is traceable to a small set of visible product signals. No opaque black box deciding what your customers see.</p><Link href="/finder/quiz_footwear" className="mt-8 inline-flex items-center gap-2 rounded-full bg-lime px-5 py-3 text-xs font-extrabold text-ink">Try the live match <ArrowRight size={14} /></Link></div><div className="bg-[radial-gradient(circle_at_75%_20%,rgba(217,255,97,.22),transparent_38%)] p-8 sm:p-12"><div className="rounded-2xl border border-white/10 bg-white/[.06] p-5"><div className="flex items-center justify-between"><span className="text-xs font-extrabold text-white/50">Recommendation trace</span><span className="rounded-full bg-lime px-2.5 py-1 text-xs font-extrabold text-ink">94% match</span></div><div className="mt-5 space-y-3">{[["Customer answer", "Weekend trails"], ["Matched tag", "trail · weight 5"], ["Matched feature", "high cushioning · weight 3"], ["Budget check", "£128 ≤ £140"], ["Selected product", "Terra Trail Runner"]].map(([label, value], i) => <div key={label} className="flex items-center gap-3 rounded-xl bg-white/[.05] p-3"><span className={`grid h-7 w-7 place-items-center rounded-lg text-xs font-extrabold ${i === 4 ? "bg-lime text-ink" : "bg-white/10"}`}>{i + 1}</span><span className="text-xs text-white/35">{label}</span><span className="ml-auto text-xs font-extrabold">{value}</span></div>)}</div></div></div></div>
        </div>
      </section>

      <section id="industries" className="bg-white px-5 py-28 lg:px-8 lg:py-36">
        <div className="mx-auto max-w-[1280px]"><p className="eyebrow text-moss">Made for considered purchases</p><div className="mt-5 flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><h2 className="max-w-4xl text-5xl font-extrabold leading-[.98] tracking-[-.065em] sm:text-7xl"><span className="block">Built for the catalogs </span><span className="block text-moss">that need guidance.</span></h2><p className="max-w-sm text-sm leading-6 text-black/50">Whenever “which one?” slows the sale, a short guided experience can turn uncertainty into momentum.</p></div><div className="mt-14 grid gap-4 sm:grid-cols-2">{industryCards.map(({ title, copy, icon: Icon, color, number }) => <article key={title} className={`group relative min-h-[330px] overflow-hidden rounded-[28px] border border-black/10 p-8 ${color}`}><div className="dot-grid absolute inset-0 opacity-15" /><div className="relative flex h-full flex-col"><div className="flex items-start justify-between"><span className="text-xs font-extrabold tracking-wider">{number}</span><span className="grid h-14 w-14 place-items-center rounded-2xl border border-black/10 bg-white/55 backdrop-blur transition group-hover:rotate-6 group-hover:scale-105"><Icon size={23} /></span></div><div className="mt-auto pt-24"><h3 className="text-3xl font-extrabold tracking-[-.055em]">{title}</h3><p className="mt-3 max-w-md text-sm leading-6 text-black/55">{copy}</p></div></div></article>)}</div></div>
      </section>

      <section className="bg-[#f2f4ee] px-5 py-28 lg:px-8 lg:py-36"><div className="mx-auto max-w-[1280px]"><p className="eyebrow text-moss">How Sellentum fits</p><h2 className="mt-5 max-w-4xl text-5xl font-extrabold leading-[.98] tracking-[-.065em] sm:text-7xl"><span className="block">Designed around the jobs </span><span className="block text-moss">commerce teams actually do.</span></h2><div className="mt-14"><StoryCarousel /></div></div></section>

      <section className="bg-white px-5 py-28 lg:px-8 lg:py-36"><div className="mx-auto grid max-w-[1280px] gap-12 lg:grid-cols-[.72fr_1.28fr] lg:items-center"><div><p className="eyebrow text-moss">A practical modern stack</p><h2 className="mt-5 text-5xl font-extrabold leading-[.98] tracking-[-.065em] sm:text-6xl">Works with the tools your MVP relies on.</h2><p className="mt-5 max-w-md text-sm leading-6 text-black/50">Import catalog data by CSV, publish to any HTML storefront, and run the production app on Supabase, OpenAI and Vercel.</p><Link href="/signup" className="mt-7 inline-flex items-center gap-2 text-xs font-extrabold text-moss">Start your workspace <ArrowRight size={13} /></Link></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{stack.map(([mark, label]) => <div key={label} className="group grid min-h-[150px] place-items-center rounded-2xl border border-black/10 bg-white p-5 text-center transition hover:-translate-y-1 hover:shadow-lg"><span><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[#f0f2ec] text-sm font-extrabold text-moss transition group-hover:bg-lime">{mark}</span><span className="mt-3 block text-xs font-extrabold">{label}</span></span></div>)}</div></div></section>

      <section id="resources" className="bg-[#f8f6f1] px-5 py-28 lg:px-8 lg:py-36"><div className="mx-auto max-w-[1280px]"><div className="flex items-end justify-between gap-6"><div><p className="eyebrow text-moss">Resources</p><h2 className="mt-5 text-5xl font-extrabold tracking-[-.065em] sm:text-7xl">See how it works.</h2></div><Link href="/signup" className="hidden items-center gap-2 text-xs font-extrabold text-moss sm:flex">Start building <ArrowRight size={13} /></Link></div><div className="mt-14 grid gap-4 lg:grid-cols-4">{[
        { label: "Shopper demo", title: "Answer three questions and see how a product finder recommends the right items.", href: "/finder/quiz_footwear", icon: Sparkles, color: "bg-lime" },
        { label: "Storefront demo", title: "See how the widget opens inside an ecommerce page before you install it.", href: "/storefront-demo", icon: Store, color: "bg-[#cbd9d0]" },
        { label: "Merchant workspace", title: "Explore products, finder questions, embed settings and analytics.", href: "/login", icon: BarChart3, color: "bg-[#d7d4ff]" },
        { label: "Setup guide", title: "Follow the first launch path from product CSV to live widget proof.", href: "/resources", icon: UploadCloud, color: "bg-[#ffd5b6]" },
      ].map(({ label, title, href, icon: Icon, color }) => <Link key={label} href={href} className="group overflow-hidden rounded-[26px] border border-black/10 bg-white"><div className={`relative grid h-52 place-items-center ${color}`}><div className="dot-grid absolute inset-0 opacity-20" /><span className="relative grid h-20 w-20 place-items-center rounded-[24px] border border-black/10 bg-white/65 backdrop-blur transition group-hover:rotate-6 group-hover:scale-105"><Icon size={29} /></span></div><div className="p-7"><p className="eyebrow text-moss">{label}</p><h3 className="mt-4 text-xl font-extrabold leading-snug tracking-[-.035em]">{title}</h3><span className="mt-6 inline-flex items-center gap-2 text-xs font-extrabold text-moss">Explore <ArrowRight size={13} /></span></div></Link>)}</div></div></section>

      <section id="pricing" className="bg-white px-5 py-28 lg:px-8 lg:py-36"><div className="mx-auto grid max-w-[1280px] overflow-hidden rounded-[32px] border border-black/10 lg:grid-cols-[.78fr_1.22fr]"><div className="relative overflow-hidden bg-lime p-9 sm:p-14"><div className="dot-grid absolute inset-0 opacity-20" /><div className="relative"><p className="eyebrow">Early-access pricing</p><h2 className="mt-5 text-5xl font-extrabold leading-[.96] tracking-[-.065em] sm:text-6xl"><span className="block">Start with one </span><span className="block">product finder. </span><span className="block">Prove it works.</span></h2><p className="mt-6 max-w-md text-sm leading-6 text-black/55">The MVP is free to explore while the first live product-finder workflow is being proven.</p></div></div><div className="p-9 sm:p-14"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div><span className="rounded-full bg-[#f1f3ed] px-3 py-1.5 text-xs font-extrabold uppercase tracking-wider">Starter workspace</span><h3 className="mt-5 text-2xl font-extrabold">Everything needed to launch a finder</h3></div><div><span className="text-5xl font-extrabold tracking-[-.06em]">£0</span><span className="text-xs text-black/35"> / month</span></div></div><div className="my-8 h-px bg-black/10" /><div className="grid gap-3 sm:grid-cols-2">{["Product catalog and CSV import", "Product finder builder", "Deterministic recommendation rules", "AI match explanations", "Embeddable storefront widget", "Journey analytics", "Brand settings", "First live proof checklist", "Demo data to explore"].map((item) => <span key={item} className="flex items-center gap-2 text-xs font-extrabold"><span className="grid h-5 w-5 place-items-center rounded-full bg-lime"><Check size={11} /></span>{item}</span>)}</div><Link href="/signup" className="mt-9 inline-flex w-full items-center justify-center gap-2 rounded-full bg-ink px-6 py-4 text-sm font-extrabold text-white">Create your workspace <ArrowRight size={15} className="text-lime" /></Link></div></div></section>

      <section className="px-5 pb-5 lg:px-8"><div className="relative mx-auto max-w-[1440px] overflow-hidden rounded-[34px] bg-ink px-6 py-24 text-center text-white sm:px-12"><div className="absolute -left-24 -top-24 h-80 w-80 rounded-full bg-lime/20 blur-3xl" /><div className="absolute -bottom-24 -right-24 h-80 w-80 rounded-full bg-peach/15 blur-3xl" /><div className="dot-grid absolute inset-0 opacity-10" /><div className="relative"><p className="eyebrow text-lime">The right product is already in your catalog</p><h2 className="mx-auto mt-6 max-w-5xl text-5xl font-extrabold leading-[.95] tracking-[-.07em] sm:text-7xl lg:text-[5.6rem]"><span className="block">Help every customer </span><span className="block">find it.</span></h2><p className="mx-auto mt-6 max-w-xl text-sm leading-6 text-white/45">Turn your product expertise into a guided buying experience that works around the clock.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/signup" className="inline-flex items-center justify-center gap-2 rounded-full bg-lime px-7 py-4 text-sm font-extrabold text-ink">Start building free <ArrowRight size={15} /></Link><Link href="/finder/quiz_footwear" className="inline-flex items-center justify-center gap-2 rounded-full border border-white/15 px-7 py-4 text-sm font-extrabold text-white">Try the live finder <ExternalLink size={14} /></Link></div></div></div></section>

      <MarketingFooter />
    </main>
  );
}
