export const platformPages = [
  {
    slug: "catalog",
    eyebrow: "Product catalog",
    title: "A clean product truth layer for every guided experience.",
    description: "Upload a CSV or manage products manually, then enrich each item with the categories, tags, features, buyer needs and links Findly needs to make reliable recommendations.",
    points: ["Manual product CRUD", "CSV import", "AI-assisted enrichment", "Structured tags, features and buyer needs"],
    proof: ["Catalog facts power quizzes, chat and configurators", "AI can enrich copy, but product selection stays deterministic", "Every product keeps a direct URL for checkout"],
    demoHref: "/dashboard/products",
    demoLabel: "Manage catalog",
  },
  {
    slug: "guided-selling",
    eyebrow: "Guided selling",
    title: "Turn your best salesperson’s questions into a digital product finder.",
    description: "Create questions, add answer options and connect each answer to product tags, categories, features or budgets. The result is a short, polished journey that narrows choice quickly.",
    points: ["Visual question builder", "Answer-level match signals", "Published storefront route", "AI-generated quiz drafts"],
    proof: ["Every answer maps to visible matching logic", "Shoppers receive 1–3 focused results", "Teams can edit and republish anytime"],
    demoHref: "/finder/quiz_footwear",
    demoLabel: "Try live finder",
  },
  {
    slug: "recommendation-engine",
    eyebrow: "Recommendation engine",
    title: "Reliable product selection before AI writes a word.",
    description: "Findly ranks products with weighted rule signals, hard budget eligibility and stable tie-breakers. AI explanations are layered on after deterministic selection.",
    points: ["Tag, category and feature scoring", "Hard budget filters", "Stable ranking", "Grounded recommendation reasons"],
    proof: ["No open-ended AI product picking", "Product recommendations are repeatable", "Merchants can understand why an item surfaced"],
    demoHref: "/finder/quiz_footwear",
    demoLabel: "See matching flow",
  },
  {
    slug: "ai-advisor",
    eyebrow: "Conversational advisor",
    title: "Let shoppers describe what they need in natural language.",
    description: "The advisor extracts requirements such as budget, use case and feature intent, then compares them against catalog facts and semantic signals before explaining the top matches.",
    points: ["Natural-language shopper input", "Budget-aware matching", "Semantic catalog comparison", "Grounded answer copy"],
    proof: ["Selection is still constrained to active products", "The assistant cannot recommend products outside the catalog", "Fallback explanations work without an API key"],
    demoHref: "/assistant/quiz_footwear",
    demoLabel: "Open advisor",
  },
  {
    slug: "configurators",
    eyebrow: "Visual configurators",
    title: "Help shoppers build compatible bundles, not impossible carts.",
    description: "Create step-by-step configuration flows with single or multi-select choices, product-linked pricing and compatibility rules that disable poor-fit combinations.",
    points: ["Configurable steps and options", "Incompatibility rules", "Live bundle pricing", "Product-linked checkout"],
    proof: ["Great for kits, bundles and fit-sensitive products", "Every choice can add tags, price and product links", "Analytics track starts, completions and buy clicks"],
    demoHref: "/configurator/config_trail_kit",
    demoLabel: "Try configurator",
  },
  {
    slug: "widget",
    eyebrow: "Embeddable widget",
    title: "Launch a guided experience on any storefront with one snippet.",
    description: "Copy the Findly script, choose the experience type, set brand colours and open a finder, advisor or configurator in a polished modal iframe.",
    points: ["Finder, advisor or configurator", "Brand colour and button text", "Modal iframe launcher", "Framework-independent JavaScript"],
    proof: ["Works on plain HTML storefronts", "No Shopify integration required for the MVP", "The same script supports multiple experiences"],
    demoHref: "/dashboard/settings",
    demoLabel: "View embed settings",
  },
  {
    slug: "analytics",
    eyebrow: "Journey analytics",
    title: "See where guided discovery turns into buying intent.",
    description: "Track widget views, journey starts, completions, surfaced products and buy button clicks across Findly’s customer-facing experiences.",
    points: ["Views", "Starts", "Completions", "Recommendations and buy clicks"],
    proof: ["Product-level performance table", "Simple funnel health view", "Works for finders, advisors and configurators"],
    demoHref: "/dashboard/analytics",
    demoLabel: "View analytics",
  },
  {
    slug: "shopper-personas",
    eyebrow: "Shopper personas",
    title: "Turn zero-party signals into launchable buyer segments.",
    description: "Findly reads guided answers, search and advisor language, configurator choices, recommendations and buy clicks, then turns them into deterministic persona plans for marketing and merchandising.",
    points: ["Segment confidence scoring", "Intent signal matrix", "Product affinity clusters", "Copyable persona packet"],
    proof: ["Segments come from event evidence, not black-box guesses", "Personas recommend the right finder, advisor, search or configurator play", "Merchants get next actions without advanced personalization complexity"],
    demoHref: "/dashboard/personas",
    demoLabel: "Open Persona Studio",
  },
] as const;

export const platformPageMap = new Map<string, (typeof platformPages)[number]>(platformPages.map((page) => [page.slug, page]));
