export const platformPages = [
  {
    slug: "catalog",
    eyebrow: "Product catalog",
    title: "A clean product truth layer for every guided experience.",
    description: "Upload a CSV or manage products manually, then enrich each item with the categories, tags, features, buyer needs and links Findly needs to make reliable recommendations.",
    points: ["Manual product CRUD", "CSV import", "AI-assisted enrichment", "Structured tags, features and buyer needs"],
    proof: ["Catalog facts power quizzes, chat and configurators", "AI can enrich copy, but product selection stays deterministic", "Every product keeps a direct URL for checkout"],
    demoHref: "/dashboard/products",
    demoLabel: "Manage catalog",
  },
  {
    slug: "catalog-pipeline",
    eyebrow: "Catalog pipeline",
    title: "Govern imports, enrichment and downstream catalog consumers.",
    description: "Findly tracks CSV contracts, manual product edits, AI enrichment, semantic readiness, field coverage, downstream experiences and telemetry feedback in one catalog pipeline center.",
    points: ["Import contract checks", "AI enrichment coverage", "Semantic discovery readiness", "Copyable catalog handoff packet"],
    proof: ["The same product truth layer feeds finders, advisor, search and configurators", "Pipeline actions are based on concrete field coverage and telemetry", "No schema migration is needed for the MVP workflow"],
    demoHref: "/dashboard/catalog-pipeline",
    demoLabel: "Open pipeline",
  },
  {
    slug: "availability-guard",
    eyebrow: "Availability Guard",
    title: "Keep unavailable products out of every recommendation path.",
    description: "Findly checks active product state, Buy Now URLs, imagery, merchandising overrides, configurator product links and analytics references before products reach shoppers.",
    points: ["Active catalog guardrails", "Buy Now URL coverage", "Stale runtime references", "Copyable availability packet"],
    proof: ["AI explanations only run after deterministic product eligibility", "Inactive products are excluded from public runtimes", "Merchants can repair stale launch references before campaigns scale"],
    demoHref: "/dashboard/availability",
    demoLabel: "Open Availability Guard",
  },
  {
    slug: "guided-selling",
    eyebrow: "Guided selling",
    title: "Turn your best salesperson’s questions into a digital product finder.",
    description: "Create questions, add answer options and connect each answer to product tags, categories, features or budgets. The result is a short, polished journey that narrows choice quickly.",
    points: ["Visual question builder", "Answer-level match signals", "Published storefront route", "AI-generated quiz drafts"],
    proof: ["Every answer maps to visible matching logic", "Shoppers receive 1–3 focused results", "Teams can edit and republish anytime"],
    demoHref: "/finder/quiz_footwear",
    demoLabel: "Try live finder",
  },
  {
    slug: "recommendation-engine",
    eyebrow: "Recommendation engine",
    title: "Reliable product selection before AI writes a word.",
    description: "Findly ranks products with weighted rule signals, hard budget eligibility and stable tie-breakers. AI explanations are layered on after deterministic selection.",
    points: ["Tag, category and feature scoring", "Hard budget filters", "Stable ranking", "Grounded recommendation reasons"],
    proof: ["No open-ended AI product picking", "Product recommendations are repeatable", "Merchants can understand why an item surfaced"],
    demoHref: "/finder/quiz_footwear",
    demoLabel: "See matching flow",
  },
  {
    slug: "ai-advisor",
    eyebrow: "Conversational advisor",
    title: "Let shoppers describe what they need in natural language.",
    description: "The advisor extracts requirements such as budget, use case and feature intent, then compares them against catalog facts and semantic signals before explaining the top matches.",
    points: ["Natural-language shopper input", "Budget-aware matching", "Semantic catalog comparison", "Grounded answer copy"],
    proof: ["Selection is still constrained to active products", "The assistant cannot recommend products outside the catalog", "Fallback explanations work without an API key"],
    demoHref: "/assistant/quiz_footwear",
    demoLabel: "Open advisor",
  },
  {
    slug: "configurators",
    eyebrow: "Visual configurators",
    title: "Help shoppers build compatible bundles, not impossible carts.",
    description: "Create step-by-step configuration flows with single or multi-select choices, product-linked pricing and compatibility rules that disable poor-fit combinations.",
    points: ["Configurable steps and options", "Incompatibility rules", "Live bundle pricing", "Product-linked checkout"],
    proof: ["Great for kits, bundles and fit-sensitive products", "Every choice can add tags, price and product links", "Analytics track starts, completions and buy clicks"],
    demoHref: "/configurator/config_trail_kit",
    demoLabel: "Try configurator",
  },
  {
    slug: "compatibility-matrix",
    eyebrow: "Compatibility Matrix",
    title: "Model dependency rules before shoppers build impossible carts.",
    description: "Findly turns configurator incompatibility rules into an auditable matrix for stale references, product-link availability, one-way dependencies and runtime QA guardrails.",
    points: ["Blocked-pair matrix", "Stale rule detection", "Linked product availability", "Copyable compatibility packet"],
    proof: ["Dependency rules stay merchant-authored and deterministic", "Configurator QA proves blocked pairs before launch", "Complex B2B-style compatibility is visible without enterprise setup"],
    demoHref: "/dashboard/compatibility",
    demoLabel: "Open Compatibility Matrix",
  },
  {
    slug: "bundle-studio",
    eyebrow: "Bundle & Attach Studio",
    title: "Increase average order value with compatible bundles.",
    description: "Findly turns configurator anchors, paid add-ons, compatibility rules and shopper telemetry into a deterministic bundle command center for ecommerce teams.",
    points: ["Product-linked anchor choices", "Paid add-on attach mapping", "Compatibility guardrail checks", "Copyable AOV lift packet"],
    proof: ["Bundle selection uses merchant-authored rules, not black-box AI", "Attach opportunities are backed by configurator telemetry", "Teams can promote safe PDP, collection and campaign bundles"],
    demoHref: "/dashboard/bundles",
    demoLabel: "Open Bundle Studio",
  },
  {
    slug: "widget",
    eyebrow: "Embeddable widget",
    title: "Launch a guided experience on any storefront with one snippet.",
    description: "Copy the Findly script, choose the experience type, set brand colours and open a finder, advisor or configurator in a polished modal iframe.",
    points: ["Finder, advisor or configurator", "Brand colour and button text", "Modal iframe launcher", "Framework-independent JavaScript"],
    proof: ["Works on plain HTML storefronts", "No Shopify integration required for the MVP", "The same script supports multiple experiences"],
    demoHref: "/dashboard/settings",
    demoLabel: "View embed settings",
  },
  {
    slug: "widget-studio",
    eyebrow: "Widget Studio",
    title: "Launch every guided experience with copy-paste storefront snippets.",
    description: "Give ecommerce teams a single desktop control center for modal and inline snippets, install contracts, attribution labels, QA checks and developer handoff packets across finder, advisor, search and configurator experiences.",
    points: ["Modal and inline snippets", "Finder, advisor, search and configurator embeds", "Install and analytics contracts", "Copyable developer handoff packet"],
    proof: ["Every snippet is generated from the same deterministic widget contract", "Attribution labels are included before storefront launch", "Storefront QA and runtime operations stay one click away"],
    demoHref: "/dashboard/widget-studio",
    demoLabel: "Open Widget Studio",
  },
  {
    slug: "headless-api",
    eyebrow: "Headless API",
    title: "Build custom guided-selling frontends on Findly’s public runtimes.",
    description: "Use the same deterministic finder, advisor, semantic search, configurator and analytics services behind the widget inside a custom storefront, agency build or headless commerce stack.",
    points: ["Finder recommendation API", "Advisor and semantic search APIs", "Configurator validation API", "Analytics event contract"],
    proof: ["Public runtimes load published resources and active catalog records server-side", "Request examples and fetch snippets are generated from the workspace", "No Supabase, OpenAI or dashboard secrets are exposed to storefront developers"],
    demoHref: "/dashboard/api-center",
    demoLabel: "Open API Center",
  },
  {
    slug: "usage-pricing",
    eyebrow: "Usage & Plan Center",
    title: "Explain SaaS plan fit before turning on billing.",
    description: "Findly meters shopper sessions, guided interactions, catalog scale, published experiences and AI-assist credits so merchants can understand future pricing without enabling Stripe billing in the MVP.",
    points: ["30-day usage meters", "Starter/Growth/Scale placeholders", "Stripe boundary notes", "Copyable billing handoff packet"],
    proof: ["Pricing drivers match guided-selling usage, not vague seat counts", "Plan recommendations are deterministic from workspace data", "No checkout, subscription or card charge is enabled in the MVP"],
    demoHref: "/dashboard/usage",
    demoLabel: "Open Usage Center",
  },
  {
    slug: "analytics",
    eyebrow: "Journey analytics",
    title: "See where guided discovery turns into buying intent.",
    description: "Track widget views, journey starts, completions, surfaced products and buy button clicks across Findly’s customer-facing experiences.",
    points: ["Views", "Starts", "Completions", "Recommendations and buy clicks"],
    proof: ["Product-level performance table", "Simple funnel health view", "Works for finders, advisors and configurators"],
    demoHref: "/dashboard/analytics",
    demoLabel: "View analytics",
  },
  {
    slug: "recommendation-feedback",
    eyebrow: "Recommendation feedback",
    title: "Let shoppers tell you when a recommendation feels right.",
    description: "Findly adds lightweight Helpful / Not right feedback to result cards, then turns those events into deterministic product risks, explanation fixes and optimization actions.",
    points: ["Result-card feedback capture", "Product quality lanes", "Negative-feedback themes", "Copyable tuning packet"],
    proof: ["Feedback does not choose products; deterministic rules still rank results", "Merchants can spot weak explanations, wrong-category matches and thin catalog evidence", "The same event contract works across finder, advisor, search and configurator surfaces"],
    demoHref: "/dashboard/feedback",
    demoLabel: "Open Feedback Center",
  },
  {
    slug: "sales-content-studio",
    eyebrow: "Sales Content Studio",
    title: "Turn product-discovery intelligence into grounded sales content.",
    description: "Findly turns catalog facts, zero-party intent, product demand and recommendation feedback into PDP, collection, email and support copy blocks that stay tied to validated product evidence.",
    points: ["Grounded PDP copy blocks", "Collection buying-guide modules", "Feedback-aware support snippets", "Copyable content packet"],
    proof: ["Copy is generated from catalog and journey evidence, not unsupported claims", "Product selection remains deterministic; content only packages proof", "Merchants get guardrails before publishing across storefront or campaign surfaces"],
    demoHref: "/dashboard/content",
    demoLabel: "Open Content Studio",
  },
  {
    slug: "merchandising-controls",
    eyebrow: "Merchandising controls",
    title: "Tune recommendation pressure without giving up determinism.",
    description: "Audit pins, boosts and exclusions against product demand, stale catalog references, stalled products and invisible SKUs before changing a live finder.",
    points: ["Pin, boost and exclude audit", "Product demand lanes", "Stale-control detection", "Copyable merchandising packet"],
    proof: ["Hard filters still run before ranking controls", "AI explanations do not choose products", "Winners and stalled products are separated before merchants add pressure"],
    demoHref: "/dashboard/merchandising",
    demoLabel: "Open Merchandising Studio",
  },
  {
    slug: "shopper-personas",
    eyebrow: "Shopper personas",
    title: "Turn zero-party signals into launchable buyer segments.",
    description: "Findly reads guided answers, search and advisor language, configurator choices, recommendations and buy clicks, then turns them into deterministic persona plans for marketing and merchandising.",
    points: ["Segment confidence scoring", "Intent signal matrix", "Product affinity clusters", "Copyable persona packet"],
    proof: ["Segments come from event evidence, not black-box guesses", "Personas recommend the right finder, advisor, search or configurator play", "Merchants get next actions without advanced personalization complexity"],
    demoHref: "/dashboard/personas",
    demoLabel: "Open Persona Studio",
  },
  {
    slug: "audience-capture",
    eyebrow: "Audience Capture",
    title: "Turn guided-selling sessions into safe zero-party audiences.",
    description: "Findly converts anonymous finder, search, advisor and configurator events into deterministic segments, consent-aware capture moments and export-ready audience packets for ecommerce teams.",
    points: ["Anonymous segment readiness", "Capture prompt planner", "Safe export schema", "Copyable audience packet"],
    proof: ["Segments come from recorded answers, queries, recommendations and buy clicks", "No CRM integration or PII storage is required in the MVP", "Consent guardrails are visible before teams export campaign audiences"],
    demoHref: "/dashboard/audience",
    demoLabel: "Open Audience Capture",
  },
  {
    slug: "returns-fit-intelligence",
    eyebrow: "Returns & fit intelligence",
    title: "Prevent wrong-fit purchases before they become returns.",
    description: "Findly reads catalog completeness, finder guardrails, compatibility rules, no-result paths, thin recommendations and stalled product clicks to show where shoppers need stronger fit guidance before checkout.",
    points: ["Product return-risk proxy", "Fit and compatibility friction signals", "Pre-purchase question guardrails", "Support-safe prevention scripts"],
    proof: ["Risk scoring comes from catalog and journey evidence, not guesses", "Merchants get concrete product, finder and configurator fixes", "The MVP does not need enterprise return-feed integrations to prevent obvious wrong-fit paths"],
    demoHref: "/dashboard/returns",
    demoLabel: "Open Returns & Fit",
  },
] as const;

export const platformPageMap = new Map<string, (typeof platformPages)[number]>(platformPages.map((page) => [page.slug, page]));
